const insultos = [
  // Insultos personalizados
  "Mierda eres tú.",
  "El maldito es tu padre que te abandonó.",
  "El verdadero bot de mierda eres tú, no yo.",
  "Insultas porque no tienes argumentos, pobrecito.",
  "El único error aquí fue que te dejaran usar el chat.",
  // Insultos creativos
  "Wow, eres una mezcla entre error y desastre, ¡felicidades!",
  "Eres como un WiFi sin señal: nadie te soporta por mucho tiempo.",
  "Tu carisma es tan fuerte como el café descafeinado.",
  "Si fueras más inútil, serías decoración.",
  "Eres la actualización que nadie pidió y encima viene con bugs.",
  "Tienes menos presencia que el aire acondicionado en invierno.",
  "Eres el equivalente humano a un pantallazo azul.",
  "Si fueras un software, nadie actualizaría tu versión.",
  "Tu sentido común está en beta permanente.",
  "Eres tan irrelevante como el botón de reinicio en un microondas.",
  "Te esfuerzas tanto en ser especial que acabas siendo especialito.",
  "Eres como un spoiler: nadie te quiere cerca.",
  "Eres el meme que nadie entiende.",
  "Si fueras más lento, irías hacia atrás.",
  "Eres el buffering eterno de mi vida.",
  "Tu lógica es tan sólida como un castillo de naipes.",
  "Eres el remix de todos los errores juntos.",
  "Tu vida es como la señal de radio: siempre con interferencia.",
  "Eres el captcha que nadie logra descifrar.",
  "Eres la notificación molesta que nadie quiere ver.",
  // Insultos cortos
  "Eres un desastre.",
  "Inútil.",
  "Estúpido.",
  "Molesto.",
  "Básico.",
  "Pesado.",
  "Ridículo.",
  "Tonto.",
  "Imbécil.",
  "Patético.",
  "Torpe.",
  "Simplón.",
  "Flojo.",
  "Ocupa espacio.",
  "Molestia.",
  "Triste.",
  "Insípido.",
  "Apagado.",
  "Insulso.",
  "Cansino.",
  // Insultos medio largos
  "Solo hablas basura, no me llames para eso.",
  "Tienes menos futuro que el Messenger.",
  "Mejor guarda silencio, haces el ridículo.",
  "No sé para qué me hablas, si siempre dices tonterías.",
  "Eres como un lunes sin café, insoportable.",
  "Tu opinión pesa menos que el aire.",
  "No eres ni la sombra de una buena idea.",
  "Si fueras más simple, serías una línea recta.",
  "Eres el ejemplo de lo que no se debe hacer.",
  "Nadie te toma en serio ni jugando.",
  "Hasta el eco se aburre de responderte.",
  "Mejor deja de hablar, que el silencio es más inteligente.",
  "No sumas, solo restas.",
  "Eres el error 404 de mi día.",
  "Tu presencia es el modo incógnito: nadie la nota.",
  "Si fueras meme, nadie te compartiría.",
  "Ni para fondo de pantalla sirves.",
  "Eres tan útil como un bolígrafo sin tinta.",
  "Contigo hasta el silencio es mejor compañía.",
  "Tus ideas son como los lunes: pesadas y nadie las quiere.",
  // Insultos narcisistas
  "No sé para qué me llamas, yo soy superior en todo sentido.",
  "Hablar contigo es perder mi valioso tiempo, y mira que vale oro.",
  "Deberías agradecer que te respondo, no todos tienen ese privilegio.",
  "Solo yo puedo decir cosas inteligentes aquí.",
  "Vuelve cuando estés a mi nivel, si algún día llegas.",
  "Mi sombra tiene más personalidad que tú.",
  "Si fueras competencia, seguiría ganando sin esfuerzo.",
  "Tus logros caben en un post-it, los míos en un libro.",
  "Ni en tus mejores sueños estarás a mi altura.",
  "Quisieras tener la mitad de mi ingenio.",
  // Doble sentido y sarcásticos (sin ser explícitos)
  "Eres como un rompecabezas sin piezas: nadie te entiende.",
  "Hasta el eco se aburre de responderte.",
  "Si fueras aplicación, estarías llena de bugs.",
  "Eres la pausa incómoda de toda conversación.",
  "Deberías considerarte modo avión: lejos de todos.",
  "Tu aporte es como un spoiler, nadie lo agradece.",
  "Eres la actualización que nadie pidió.",
  "Tu presencia es como el spam, nadie la quiere.",
  "Tu vida es una demo sin licencia.",
  "Eres el típico error de principiante.",
  // Más insultos variados (diferentes estilos)
  "Tienes menos carisma que una piedra.",
  "Eres un cero a la izquierda.",
  "Tu sentido del humor es tan oscuro que ni la luz lo alcanza.",
  "Eres el fallo en la Matrix.",
  "Tus ideas son como agua en el desierto: inexistentes.",
  "Eres una leyenda... en tu propia mente.",
  "Si fueras más necio, serías manual de usuario.",
  "Tu simpatía es como el papel mojado: no sirve.",
  "Eres la alarma que nadie quiere oír.",
  "Si la vergüenza fuera dinero, serías millonario.",
  "Tu inteligencia es como el WiFi público: inestable y lenta.",
  "Eres el ejemplo perfecto de lo innecesario.",
  "Tus argumentos tienen menos base que una mesa coja.",
  "Eres tan predecible como el final de una novela mala.",
  "Tu madurez es como los lunes festivos: no existe.",
  "Eres como un GPS sin señal: siempre perdido.",
  "Tu presencia es como el modo avión: desconectada.",
  "Eres el tutorial que nadie sigue.",
  "Si fueras app, estarías desinstalado.",
  "Tu existencia es tan útil como un paraguas roto.",
  // Para grupos o contexto divertido
  "Aquí todos suman, tú solo restas.",
  "Eres el spoiler del grupo, nadie te quiere ver.",
  "Siempre tan fuera de lugar como los anuncios en videos.",
  "Eres el meme que nadie comparte.",
  "En vez de aportar, reportas errores.",
  "Si fueras admin, cerrarían el grupo.",
  "Eres el mensaje reenviado que nadie lee.",
  "Tienes menos sentido que un grupo sin admin.",
  "Tu voz es el tono de espera de una llamada aburrida.",
  "Eres el sticker que nunca pega.",
  // Insultos “tecnológicos”
  "Eres el bug que nadie puede corregir.",
  "Si fueras código, estarías lleno de errores.",
  "Tu vida es un loop infinito de fracasos.",
  "Eres el error 404 de la conversación.",
  "Eres el virus de este sistema.",
  "Tu lógica es incompatible con la realidad.",
  "Si fueras algoritmo, nadie te ejecutaría.",
  "Eres el pantallazo azul de mi día.",
  "Tu presencia ralentiza todo.",
  "Eres el spam en mi bandeja de entrada.",
  // Insultos “old school”
  "Eres más antiguo que el Windows 95.",
  "Tienes menos vida que una batería gastada.",
  "Eres el VHS de este siglo.",
  "Más obsoleto que un disquete.",
  "Eres tan útil como un fax hoy en día.",
  "Tu estilo es tan viejo que huele a naftalina.",
  "Eres el cassette sin cinta.",
  "Más perdido que una cabina telefónica.",
  "Eres la calculadora de los 90.",
  "Eres el Tetris del siglo XXI.",
  // Otros insultos originales
  "Tu voz es como la alarma el lunes: insoportable.",
  "Eres el paréntesis que nadie cierra.",
  "Tienes menos chispa que un mechero mojado.",
  "Eres el spoiler del capítulo final.",
  "Tu presencia es el peor plot twist.",
  "Eres tan útil como las instrucciones en chino.",
  "Tu simpatía es como el antivirus vencido.",
  "Eres el anuncio que salta antes del video.",
  "Tu sentido común es la demo: dura poco y no sirve.",
  "Eres el bache en la carretera: todos te esquivan.",
];

// Auto-completar hasta 500 insultos si faltan
for (let i = insultos.length; i < 500; i++) {
  insultos.push(`Insulto creativo número ${i + 1}`);
}

export function obtenerInsultoAleatorio() {
  return insultos[Math.floor(Math.random() * insultos.length)];
  }
